AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Decode Digital - RDS Database
Parameters:
  DBSubnets:
    Description: The VPC and subnets to set up the db in. Private.
    Type: 'List<AWS::EC2::Subnet::Id>'
  DBInstanceType:
    Default: db.t2.micro
    Description: The database instance type
    Type: String
  DBInstanceStorage:
    Default: '20'
    Type: String
  DBIDName:
    Default: db
    Description: The database instance name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBName:
    Default: database
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    Default: admin
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '32'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters, at least 8 characters
  AppSecurityGroups:
    Description: Instance security group
    Type: 'AWS::EC2::SecurityGroup::Id'
  AppTagName:
    Default: ENV-CLIENT
    Description: Name of your app, tag gets applied to all resources, environment-client's name
    Type: String
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBIDName
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBInstanceStorage
      DBInstanceClass: !Ref DBInstanceType
      Engine: MySQL
      EngineVersion: 5.7.22
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBParameterGroupName: decode-rds
      VPCSecurityGroups:
        - !Ref AppSecurityGroups
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Ref AppTagName

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: "Private database subnets for the RDS database."
      DBSubnetGroupName: !Ref AppTagName
      SubnetIds: !Ref DBSubnets
Outputs:
  DBCreds:
    Description: Connection credentials for DB
    Value: !Join 
      - ''
      - - 'RDS Endpoint:'
        - !GetAtt 
          - MyDB
          - Endpoint.Address
        - ':'
        - !GetAtt 
          - MyDB
          - Endpoint.Port
        - /
        - !Ref DBName
